### ISSUE TITLE
Add CI via github actions

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-app#3]
Ideally via github actions:

at least:
 - run (go) tests

ideally:
 - test coverage reporting
 - integration / e2e tests

**Comment by marbar3778** [comment]
For the most part you can copy https://github.com/cosmos/cosmos-sdk/tree/master/.github/workflows. If you have any questions let me know, I did the migration to github actions for the cosmos/tendermint repos.

**Comment by evan-forbes** [comment]
thanks!

**Comment by evan-forbes** [comment]
@marbar3778 There are quite a few tests/checks that rely on simapp. Should I cut those, or incorporate those tests to use lazyledger-app instead of simapp? Would that be redundant, since those checks are already done in the cosmos-sdk?

**Comment by marbar3778** [comment]
you will want to have them use lazyledger-app. It is some duplication but we dont know if we will only use modules from the lazyledger-sdk
