### ISSUE TITLE
clean up imports

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-app#4]
I quickly skimmed through the imports and it seems that the app imports a mixture of lazyledger-core and github.com/tendermint/tendermint.

**Comment by liamsi** [comment]
Actually, the replace directive should make this unnecessary.. But, we should make sure that this actually worked. One thing I've noticed with this regard is that versions of the dependency and the replace version diverge:
https://github.com/lazyledger/lazyledger-app/blob/05e056d8e21e339c9460451ba9d5db560f96aaa1/go.mod#L16
https://github.com/lazyledger/lazyledger-app/blob/05e056d8e21e339c9460451ba9d5db560f96aaa1/go.mod#L26

**Comment by liamsi** [comment]
I think that minor version glitch leads to not having the desired effect and the module used is still tendermint/tendermint instead of lazsledger/lazyledger-core.

Changing the replace to:
`github.com/tendermint/tendermint v0.34.1 => github.com/lazyledger/lazyledger-core v0.0.0-20201215200419-0332760f7e24` yields:
```
go: github.com/lazyledger/lazyledger-app/app imports
        github.com/tendermint/tendermint/abci/types imports
        github.com/lazyledger/lazyledger-core/crypto/ed25519: github.com/lazyledger/lazyledger-core@v0.32.7: parsing go.mod:
        module declares its path as: github.com/tendermint/tendermint
                but was required as: github.com/lazyledger/lazyledger-core
``` 

I'm not sure we can use the replace directive like this.

**Comment by evan-forbes** [comment]
if a version or commit hash is added to the end of the lazyledger-core replace directive, it does replace, but it causes more errors (which could mean it's working!). I could swear I've used the replace directive before exactly like this, but if I can't get it work, I'll replace directly as mentioned in [#2](https://github.com/lazyledger/cosmos-sdk/issues/2). That's more explicit too.

**Comment by liamsi** [comment]
Yeah, that definitely works and there I don't see any reason why not to use the "correct" imports in new code (unless we want to generate the boilerplate again; then we'd need to repeat the search&replace procedure but that that should be simple enough)

**Comment by liamsi** [comment]
This might mean that you have to replace the imports in the SDK fork first. Not sure if go will be happy with to "different" types.
