### ISSUE TITLE
Decide what to do about missing logging flags for the start sub-command 

### ISSUE THREAD

**Issue by evan-forbes** [lazyledger/lazyledger-app#9]
[Logging has been refactored](https://github.com/cosmos/cosmos-sdk/pull/8072/files) in the cosmos-sdk. Starport apps have yet to be updated accordingly, so these flags have to be manually added to the `start` sub-command in order to pass the logging configurations to lazyledger-core.

I see two very easy solutions to this, we could 
1. add the flags to the [start cmd](https://github.com/lazyledger/cosmos-sdk/blob/3addd7f65d1c35f76716d67641ee629b01f5b9c7/server/start.go#L68) in the lazyledger fork of the cosmos-sdk
2. add the flags outside of the sdk in the [lazyledger-app](https://github.com/lazyledger/lazyledger-app/blob/6ed66f9377e233c104ff4cf34ee2f3fbf231233a/cmd/lazyledger-appd/cmd/root.go#L112)
3. Something else that I'm not seeing (@marbar3778 @liamsi)

Ideally, we would add them to the cosmos-sdk, right next to other `start` sub-command flags. However, any changes we make to the sdk will have to be undone each time we upstream anything.

**Comment by marbar3778** [comment]
Weird. I always assumed it was there. On tendermint we have this as a global flag on the start cmd. I dont have a preference, whichever is easiest. 

We should open an issue on the cosmos-sdk to add support this as well. If you decide to add it on the sdk side you can also look at upstreaming the change.

**Comment by evan-forbes** [comment]
Ok, I found out exactly what was wrong after talking with @liamsi and a little more digging. The cosmos-sdk is adding the flags when calling [`Execute`](https://github.com/cosmos/cosmos-sdk/blob/c95de9c4177442dee4c69d96917efc955b5d19d9/server/cmd/execute.go#L32). The lazyledger-app call's its own [`Execute`](https://github.com/lazyledger/lazyledger-app/blob/9b2bbba6535767132c62d59d898fa62a90b1b778/cmd/lazyledger-appd/cmd/root.go#L78). Therefore, it makes sense to add the flags to the lazyledger-app's `Execute` command in the same fashion. This was changed in starport `v0.13.2`, so we don't need to upstream anything.
